name : "saas project deployment"

on:
  push :
    branches :
    - main


jobs:
  code-check:
    run-on : ubuntu-latest
 
    steps:
      - name : checkout code 
        uses : action/checkout@v3
      
      - name: uv install
        uses: astral-sh/setup-uv@v4
        with:
          version : latest
      
      - name : install dependency
        runs : uv sync
        
      - name: Server start karo
        run: |
             cd backend
             uv run uvicorn main:app --host 0.0.0.0 --port 8000 &
             uv run celery -A src.celery.celery_app worker     

      - name: Server health check
        run: |
         curl http://localhost:8000/health
  


    