name : "saas project deployment"

on:
  push :
    branches :
    - main


jobs:
  code-check:
    runs-on : ubuntu-latest
 
    steps:
      - name : checkout code 
        uses : actions/checkout@v3
      
      - name: uv install
        uses: astral-sh/setup-uv@v4
        with:
          version : latest
      
      - name : install dependency
        run : uv sync
      - name: Env file banao
        run: echo "${{ secrets.ENV_FILE }}" > .env
        
      - name: Server start karo
        run: |
            uv run celery -A src.celery.celery_app worker & 
            sleep 3                                           
            uv run uvicorn main:app --host 0.0.0.0 --port 8000 &  
            sleep 5                  

      - name: Server health check
        run: |
         curl http://localhost:8000/health
  


    